### ISSUE TITLE
Does Not Compile On PowerPC MacOS

### ISSUE THREAD

**Issue by DetourNetworkUK** [fcorbelli/zpaqfranz#69]
The [MacOS Quick Start Guide](https://github.com/fcorbelli/zpaqfranz/wiki/Quickstart-Mac) Lists The Following Command To Use For Compiling On PowerPC MacOS:
`g++ -O3 -DBIG -DANCIENT -Dunix -DNOJIT zpaqfranz.cpp -o zpaqfranz -pthread`
I Was Unable To Get This Command To Work On A PowerPC G4 Mac Mini On 10.5.8 Or A PowerMac G5 On 10.5.8, Both Using G++@4.0.1, As The Compilation Fails With The Following Error:
```
zpaqfranz.cpp:72: error: ‘size_t’ does not name a type
zpaqfranz.cpp: In function ‘int64_t myatoll(const char*)’:
zpaqfranz.cpp:21276: error: ‘strnlen’ was not declared in this scope
```
The Same Error Occurs When Using G++@4.2.0 And GCC@7.5.0 (With The Latter In C++ 2011 Mode).
Find Attached The G++@4.0.1, G++@4.2.0, And GCC@7.5.0 Logfiles.

[G++ 4.0.1](https://github.com/fcorbelli/zpaqfranz/files/12582539/ZPAQFRANZLOGFILEGPP401.txt)
[G++ 4.2.0](https://github.com/fcorbelli/zpaqfranz/files/12582545/ZPAQFRANZLOGFILEGPP420.txt)
[GCC 7.5.0](https://github.com/fcorbelli/zpaqfranz/files/12582549/ZPAQFRANZLOGFILEGCC750.txt)

**Comment by fcorbelli** [comment]
Thank you, it is definitely my mistake
(it's been a while since I turned on my minimac :)

The updated zpaqfranz.cpp 58.10g, marked 2023-09-12, compiles OK on gcc 4.2  
```
28 Thanks to https://github.com/DetourNetworkUK         for Mac PowerPC strnlen bug
```

![1](https://github.com/fcorbelli/zpaqfranz/assets/77727889/6c2420f8-179f-4b85-a146-41525212f320)

**Comment by DetourNetworkUK** [comment]
Can Confirm That This New Version Is Compiling :)
